POST http://localhost:8080/login HTTP/1.1
content-type: application/json

{
    "email": "anita.borg@systers.xyz",
    "password": "123456"
}

//USUARIOS

GET http://localhost:8080/users HTTP/1.1
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFuaXRhLmJvcmdAc3lzdGVycy54eXoiLCJpYXQiOjE2ODkyNzQyODQsImV4cCI6MTY4OTI3Nzg4NCwic3ViIjoiMSJ9.ppqnI2WyZc-R3IvHLqMnlx1r1MamoUzsy0O269Sonzc


POST http://localhost:8080/users HTTP/1.1
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFuaXRhLmJvcmdAc3lzdGVycy54eXoiLCJpYXQiOjE2ODkyNzQyODQsImV4cCI6MTY4OTI3Nzg4NCwic3ViIjoiMSJ9.ppqnI2WyZc-R3IvHLqMnlx1r1MamoUzsy0O269Sonzc

{
    "email": "admin@burgerqueen.com",
    "password": "123456",
    "role": "admin"
}


//PRODUCTOS

GET http://localhost:8080/products/2 HTTP/1.1
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImdyYWNlLmhvcHBlckBzeXN0ZXJzLnh5eiIsImlhdCI6MTY4ODUxMzA5OSwiZXhwIjoxNjg4NTE2Njk5LCJzdWIiOiIyIn0.-UKu4cKMR5DLxwrU2uhNw2NZ28uThcLolbbMxvuat8A

PATCH http://localhost:8080/products/2 HTTP/1.1
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImdyYWNlLmhvcHBlckBzeXN0ZXJzLnh5eiIsImlhdCI6MTY4ODUxMzM4NSwiZXhwIjoxNjg4NTE2OTg1LCJzdWIiOiIyIn0.2YHf3hhMwXOO5tsyBxXxNB7gtsD88zE7KlplIXpL6-s

{
    "id": 2,
    "name": "Café americano",
    "price": 500,
    "image": "https://raw.githubusercontent.com/marielfico/DEV005-burger-queen-api-client/moni2/burger%20queen/src/assets/img/products/cafe-americano.png",
    "type": "Desayuno"
}


//ORDENES

GET http://localhost:8080/orders/1 HTTP/1.1
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImdyYWNlLmhvcHBlckBzeXN0ZXJzLnh5eiIsImlhdCI6MTY4OTAxNDg0NiwiZXhwIjoxNjg5MDE4NDQ2LCJzdWIiOiIyIn0.IAIBNajDVxcie8PcyBoW5OacnIlSsld1o6pF4QbORNg

PATCH http://localhost:8080/orders/2 HTTP/1.1
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImdyYWNlLmhvcHBlckBzeXN0ZXJzLnh5eiIsImlhdCI6MTY4ODYxMDc0OCwiZXhwIjoxNjg4NjE0MzQ4LCJzdWIiOiIyIn0.5hPmmjuw7f6droJVgMHfy8754GvTswAVOYQXdonfXKw

{
    "status": "delivered",
    "dateProcessed": "2022-03-05 16:00"
}

POST http://localhost:8080/orders HTTP/1.1
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImdyYWNlLmhvcHBlckBzeXN0ZXJzLnh5eiIsImlhdCI6MTY2NjEyNTQ5NSwiZXhwIjoxNjY2MTI5MDk1LCJzdWIiOiIyIn0.laNI7HKXIcDzCp1AYl4aMWh5jSlcMFKFQLHrCC2XTPw

{
    "client": "Harry Potter",
    "products": [
        {
            "qty": 1,
            "product": {
            "id": 1,
            "name": "Sandwich de jamón y queso",
            "price": 1000,
            "image": "https://github.com/Laboratoria/bootcamp/tree/main/projects/04-burger-queen-api/resources/images/sandwich.jpg",
            "type": "Desayuno",
            "dateEntry": "2022-03-05 15:14:10"
            }
        },
        {
            "qty": 1,
            "product": {
            "id": 2,
            "name": "Café americano",
            "price": 500,
            "image": "https://github.com/Laboratoria/bootcamp/tree/main/projects/04-burger-queen-api/resources/images/coffe.jpg",
            "type": "Desayuno",
            "dateEntry": "2022-03-05 15:14:10"
            }
        }
    ],
    "status": "pending",
    "dataEntry": "2022-03-05 15:00"
}